In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9297, 2303, 2727, 6269],
 [9297, 2303, 2727, 3906],
 [9297, 3091, 2727, 7882],
 [4836, 7195, 778, 5460, 278],
 [4836, 7195, 778, 5460, 9210],
 [8611, 9297, 6922, 2727, 3463],
 [9353, 5469, 4983, 5460]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9297 2303 2727 6269]
 [   0    0    0    0 9297 2303 2727 3906]
 [   0    0    0    0 9297 3091 2727 7882]
 [   0    0    0 4836 7195  778 5460  278]
 [   0    0    0 4836 7195  778 5460 9210]
 [   0    0    0 8611 9297 6922 2727 3463]
 [   0    0    0    0 9353 5469 4983 5460]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 284ms/step


array([[[ 0.00963516, -0.02504826,  0.03809242, -0.01405865,
         -0.0024796 ,  0.03078855, -0.0226227 , -0.04764614,
          0.02694095, -0.02934042],
        [ 0.00963516, -0.02504826,  0.03809242, -0.01405865,
         -0.0024796 ,  0.03078855, -0.0226227 , -0.04764614,
          0.02694095, -0.02934042],
        [ 0.00963516, -0.02504826,  0.03809242, -0.01405865,
         -0.0024796 ,  0.03078855, -0.0226227 , -0.04764614,
          0.02694095, -0.02934042],
        [ 0.00963516, -0.02504826,  0.03809242, -0.01405865,
         -0.0024796 ,  0.03078855, -0.0226227 , -0.04764614,
          0.02694095, -0.02934042],
        [-0.03643104,  0.00842432, -0.00261322, -0.04752867,
          0.04570457, -0.04958843, -0.02106994, -0.0292895 ,
          0.03516776,  0.04825134],
        [-0.04687115, -0.01497229,  0.03078609, -0.04840105,
         -0.0056318 ,  0.02507151,  0.04550871, -0.02447036,
          0.01192579, -0.01320317],
        [-0.04289352,  0.00618104,  0.03350723, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 9297, 2303, 2727, 6269])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 66ms/step


array([[ 0.00963516, -0.02504826,  0.03809242, -0.01405865, -0.0024796 ,
         0.03078855, -0.0226227 , -0.04764614,  0.02694095, -0.02934042],
       [ 0.00963516, -0.02504826,  0.03809242, -0.01405865, -0.0024796 ,
         0.03078855, -0.0226227 , -0.04764614,  0.02694095, -0.02934042],
       [ 0.00963516, -0.02504826,  0.03809242, -0.01405865, -0.0024796 ,
         0.03078855, -0.0226227 , -0.04764614,  0.02694095, -0.02934042],
       [ 0.00963516, -0.02504826,  0.03809242, -0.01405865, -0.0024796 ,
         0.03078855, -0.0226227 , -0.04764614,  0.02694095, -0.02934042],
       [-0.03643104,  0.00842432, -0.00261322, -0.04752867,  0.04570457,
        -0.04958843, -0.02106994, -0.0292895 ,  0.03516776,  0.04825134],
       [-0.04687115, -0.01497229,  0.03078609, -0.04840105, -0.0056318 ,
         0.02507151,  0.04550871, -0.02447036,  0.01192579, -0.01320317],
       [-0.04289352,  0.00618104,  0.03350723, -0.03004624, -0.04457778,
        -0.00365803,  0.01478246,  0.0279266 